backend:
  name: git-gateway
  repo: masterbirdy/sophia-website
  branch: master

media_folder: static/assets
public_folder: assets

media_library:
  name: cloudinary
  config:
    cloud_name: duq22ievt
    api_key: 921837964991945
    media_folder: "static/assets"
    public_folder: "assets"

collections:
  - name: projects
    label: Project
    folder: projects
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project-item",
        }
      - { name: title, label: Title, widget: string }
      - { name: subtitle, label: Subtitle, widget: string, required: false }
      - {
          name: featuredimage,
          label: Featured Image,
          widget: image,
          allow_multiple: false,
        }
      - { name: images, label: Images, widget: image, required: false }
      - { name: description, label: Description, widget: "text" }
      - { name: tags, label: tags, widget: list }
  - name: webpages
    label: Webpage
    files:
      - name: contact-us
        file: src/pages/contact-us/index.md
        label: Contact Us
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-us",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - name: press
        file: src/pages/press/index.md
        label: Press
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "press",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - name: returns
        file: src/pages/returns/index.md
        label: "Returns & Exchanges"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "returns",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Large Word", name: largeword, widget: string }
          - { label: Body, name: body, widget: markdown }
