backend:
  name: git-gateway
  repo: masterbirdy/sophia-website
  branch: master

media_folder: static/assets
public_folder: assets

media_library:
  name: cloudinary
  config:
    cloud_name: duq22ievt
    api_key: 921837964991945
    media_folder: "static/assets"
    public_folder: "assets"

collections:
  - name: socialmedia
    label: Social Media
    files:
      - name: social-media
        file: src/socialmedia/index.md
        label: Social Media
        fields:
          - { name: instagram, label: Instagram, widget: string }
          - { name: pinterest, label: Pinterest, widget: string }
          - { name: youtube, label: Youtube, widget: string }
          - { name: twitter, label: Twitter, widget: string }

  - name: projects
    label: Project
    folder: projects
    create: true
    media_library:
      name: cloudinary
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project-item",
        }
      - { name: title, label: Title, widget: string }
      - { name: subtitle, label: Subtitle, widget: string, required: false }
      - {
          name: featuredimage,
          label: "Featured Image",
          widget: image,
          allow_multiple: false,
        }
      - {
          name: featuredmovingimage,
          label: "Featured Moving Image",
          widget: image,
          allow_multiple: false,
        }
      - { name: doodle, label: "Doodle", widget: number }
      - { name: year, label: "Year", widget: string }
      - label: Images
        name: images
        widget: image
        options:
          media_library:
            config:
              multiple: true
      - { name: description, label: Description, widget: "text" }
      - { name: tags, label: Tags, widget: list }
      - { name: link, label: Link, widget: string, required: false }
      - {
          name: youtubelink,
          label: Youtube Link,
          widget: string,
          required: false,
        }
      - {
          name: instagramlink,
          label: Instagram Link,
          widget: string,
          required: false,
        }
      - {
          name: spotifylink,
          label: Spotify Link,
          widget: string,
          required: false,
        }
  - name: webpages
    label: Webpage
    files:
      - name: contact-us
        file: src/pages/contact-us/index.md
        label: Contact Us
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-us",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - name: press
        file: src/pages/press/index.md
        label: Press
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "press",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - name: returns
        file: src/pages/returns/index.md
        label: "Returns & Exchanges"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "returns",
            }
          - { label: Title, name: title, widget: string }
          - { label: "Large Word", name: largeword, widget: string }
          - { label: Body, name: body, widget: markdown }
      - name: view-featured
        file: src/pages/view-featured/index.md
        label: "View Featured"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "view-featured",
            }
          - {
              label: First Item,
              name: firstitem,
              widget: relation,
              collection: projects,
              searchFields: ["title"],
              valueField: "{{slug}}",
              displayFields: ["title", "featuredimage"],
            }
