backend:
  name: test-repo
  repo: masterbirdy/sophia-website
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - name: projects
    label: Project
    folder: projects
    slug: "{{title}}"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "project-item",
        }
      - { name: title, label: Title, widget: string }
      - { name: subtitle, label: Subtitle, widget: string, required: false }
      - {
          name: featuredimage,
          label: Featured Image,
          widget: image,
          allow_multiple: false,
        }
      - { name: images, label: Images, widget: image, required: false }
      - { name: description, label: Description, widget: "text" }
      - { name: tags, label: tags, widget: list }
  - name: webpages
    label: Webpage
    files:
      - name: contact-us
        file: src/pages/contactus/index.md
        label: Contact Us
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "contact-us",
            }
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
